### ISSUE TITLE
【LP】デザインの参考にするサイトやテンプレートを収集する

### ISSUE THREAD

**Issue by y-uchiida** [commew/timelogger-lp#12]
# 作業期間  
2023/04/15 まで

# 内容
timmew のLPデザインを作成するにあたって、参考にしたいサイトやテンプレートなどを収集します  
情報は以下のWiki ページに集約します  
[LPデザイン作成の参考サイトなど](https://github.com/commew/timelogger-lp/wiki/LP%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E4%BD%9C%E6%88%90%E3%81%AE%E5%8F%82%E8%80%83%E3%82%B5%E3%82%A4%E3%83%88%E3%81%AA%E3%81%A9)

**Comment by oreojinyuu34** [comment]
Toggl - Time Tracker & Employee Timesheet Software
https://toggl.com/
Focus Keeper - Time Management App
https://focuskeeper.co/

**Comment by y-uchiida** [comment]
@ai-ura @oreojinyuu34 
ご対応ありがとうございました！今朝のミーティングでお話しした通り、現在収集してある内容でワイヤーフレーム作成に着手していただければと思います。  
こちらのissue は以上で終了といたします。
