### ISSUE TITLE
【LP】サイトコーディング

### ISSUE THREAD

**Issue by y-uchiida** [commew/timelogger-lp#15]
# 作業期間
2023/5/27 まで(仮)

# 内容  
画面カンプに基づいて、LPサイトのコーディングを行っていきます。

**Comment by oreojinyuu34** [comment]
gitの使い方の理解不足でJSONファイルをプッシュしてしまいました。
簡単に消せなかったので、後日消し方を調べて消去します

**Comment by oreojinyuu34** [comment]
ファビコン完了
